version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: rest_api_postgres
    environment:
      POSTGRES_DB: rest_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rest_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_api_app
    environment:
      PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DB: rest_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rest_api_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  rest_api_network:
    driver: bridge
